"use strict";
const REPO="retrocraft0-hub/Q-Downloads";
const P=["Q-System","Q-Core","Q-Entity","Q-Chunky","Q-Player"];
const I18N=window.Q_I18N||{names:{de:"Deutsch","en-US":"English"},texts:{}};
const T={
de:{catalog:"Downloads",select:"Wähle dein Projekt",desc:"Das gesamte Q-Portfolio – einzeln oder als Gesamtpaket. Wähle erst das Produkt, dann die Plattform und Minecraft-Version.",catalogButton:"Produkte ansehen",releaseButton:"Alle GitHub-Releases",prodTitle:"Fünf Projekte. Eine Familie.",prodText:"Klicke auf ein Produkt, um verfügbare Originaldateien zu finden.",s1:"Produkt",s2:"Plattform",s3:"Minecraft-Version",s4:"Q-Version",choose:"Bitte auswählen",chooseProduct:"Produkt über die Karten auswählen",choosePlatform:"Erst Plattform auswählen",chooseMC:"Erst Minecraft auswählen",chooseVersion:"Alle Q-Versionen",browseTitle:"Finde deine Version",browseText:"Nur nachweislich veröffentlichte JARs. Die Auswahl baut sich Schritt für Schritt auf.",reset:"Auswahl zurücksetzen",noChoose:"Wähle oben eine Produktkarte.",results:"Download-Dateien",files:"Dateien",loading:"Katalog wird geladen …",none:"Hierfür sind noch keine Dateien veröffentlicht.",error:"Katalog vorübergehend nicht erreichbar.",useReleases:"Öffne stattdessen das GitHub-Releasearchiv.",download:"JAR herunterladen ↓",details:"Release-Details ↗",test:"TESTVERSION",approved:"FREIGEGEBEN",more:"Weitere Dateien",all:"Alle",noticeTitle:"Zu Entwicklungsständen",notice:"-dev bedeutet technisch gebaut und geprüft, aber nicht vollständig im Minecraft-Spielbetrieb getestet. Bitte Backup machen und zuerst testen.",system:"Das komplette Paket: Core, Chunky, Entity und Player in einem.",core:"Budgets, Ressourcen und Headroom intelligent verwalten.",entity:"Entities und Beobachter effizient koordinieren.",chunky:"Chunk-Aufgaben priorisieren und gezielt verteilen.",player:"Join, Respawn, Tracking und Dimensionswechsel.",explore:"Projekt auswählen ↗",learn:"Mehr entdecken",origin:"Die Geschichte von Q",about:"Über die Q-Reihe",qbot:"Qbot & Entwicklung",help:"Feedback",version:"Version",open:"Downloads öffnen",searchNav:"Suche",searchEyebrow:"DIREKTSUCHE",searchTitle:"Finde deine Datei direkt.",searchHelp:"Alle Original-Releases durchsuchen – auch ohne vorher ein Produkt auszuwählen.",searchLabel:"Nach Produkt, Plattform, Minecraft- oder Q-Version suchen",searchPlaceholder:"z. B. Q-System Paper 1.21.11",searchReset:"Suche leeren",searchInitial:"Neueste Originaldownloads",searchResults:"Suchergebnisse",searchEmpty:"Keine passende Originaldatei gefunden.",searchHint:"Wähle ein anderes Stichwort oder öffne alle Releases."},
"en-US":{catalog:"The product catalogue",select:"Choose a project",desc:"The Q portfolio: individual components or a complete package. Choose a product, platform and Minecraft version.",catalogButton:"Browse products",releaseButton:"All GitHub releases",prodTitle:"Five projects. One family.",prodText:"Choose a product card to browse genuine published downloads.",s1:"Product",s2:"Platform",s3:"Minecraft version",s4:"Q version",choose:"Please choose",chooseProduct:"Pick a product card first",choosePlatform:"Choose platform first",chooseMC:"Choose Minecraft first",chooseVersion:"All Q versions",browseTitle:"Find your version",browseText:"Only published original JARs. The selection proceeds step by step.",reset:"Reset selection",noChoose:"Select a product card above.",results:"Downloads",files:"files",loading:"Loading catalogue …",none:"No releases for this combination yet.",error:"Catalogue temporarily unavailable.",useReleases:"Open GitHub releases instead.",download:"Download JAR ↓",details:"Release details ↗",test:"DEVELOPMENT",approved:"APPROVED",more:"Load more",all:"All",noticeTitle:"About development builds",notice:"-dev means built and structurally verified, not yet fully Minecraft-tested. Back up first and use a test installation.",system:"All-in-one bundle: Core, Chunky, Entity and Player.",core:"Manage resource budgets and server headroom.",entity:"Coordinate entities and their observers.",chunky:"Prioritise and distribute chunk operations.",player:"Join, respawn, tracking and dimension changes.",explore:"Select project ↗",learn:"Learn more",origin:"History of Q",about:"About Q",qbot:"Qbot & development",help:"Feedback",version:"Version",open:"Open downloads",searchNav:"Search",searchEyebrow:"DIRECT SEARCH",searchTitle:"Find your file instantly.",searchHelp:"Search all original releases – no need to select a product first.",searchLabel:"Search product, platform, Minecraft or Q version",searchPlaceholder:"e.g. Q-System Paper 1.21.11",searchReset:"Clear search",searchInitial:"Latest original downloads",searchResults:"Search results",searchEmpty:"No matching original downloads.",searchHint:"Try another term or browse all releases."}};
let locale="de", all=[],project="",ready=false,loadError="",visible=16;
function language(){try{const saved=localStorage.getItem("q_download_language");if(saved&&I18N.names[saved])return saved}catch(_){}const browsers=[...(navigator.languages||[]),navigator.language||""];for(const lang of browsers){if(I18N.names[lang])return lang;const prefix=lang.split("-")[0];const found=Object.keys(I18N.names).find(k=>k===prefix||k.startsWith(prefix+"-"));if(found)return found}return "de"}
locale=language();
function L(k){const base=T[locale]||T[(locale||"").startsWith("de")?"de":"en-US"];return I18N.texts?.[locale]?.[k]||base[k]||T.de[k]||k}
function el(tag,cl,txt){const a=document.createElement(tag);if(cl)a.className=cl;if(txt!==undefined)a.textContent=txt;return a}
function link(url,label,cl){const a=el("a",cl,label);a.href=url;a.rel="noopener noreferrer";return a}
function cmpVersion(a,b){const pa=String(a).match(/\d+|[^\d]+/g)||[],pb=String(b).match(/\d+|[^\d]+/g)||[];for(let i=0;i<Math.max(pa.length,pb.length);i++){const x=pa[i]||"",y=pb[i]||"";const c=/^\d+$/.test(x)&&/^\d+$/.test(y)?Number(x)-Number(y):x.localeCompare(y);if(c)return c}return 0}
const unique=(a)=>[...new Set(a)];
function options(node,values,placeholder){const prev=node.value;node.replaceChildren(new Option(placeholder,""),...values.map(x=>new Option(x,x)));node.value=values.includes(prev)?prev:""}
function setLang(){document.documentElement.lang=locale;document.querySelectorAll("[data-t]").forEach(e=>{e.textContent=L(e.dataset.t)});document.querySelectorAll("[data-t-placeholder]").forEach(e=>{e.placeholder=L(e.dataset.tPlaceholder)});document.querySelectorAll(".product-card").forEach(c=>{c.querySelector(".prod-description").textContent=L(c.dataset.desc);c.querySelector(".prod-foot").textContent=L("explore")});document.querySelector("#locale").value=locale;updateFilters();render();renderSearch()}
function initLocale(){const sel=document.querySelector("#locale");if(!sel)return;for(const [code,name] of Object.entries(I18N.names)){sel.add(new Option(name,code))}sel.value=locale;sel.addEventListener("change",()=>{locale=sel.value;try{localStorage.setItem("q_download_language",locale)}catch(_){}setLang()})}
function choose(p){project=p;visible=16;document.querySelectorAll(".product-card").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.product===p)));const area=document.getElementById("browser");area.hidden=false;document.getElementById("chosenProduct").textContent=p;for(const id of ["platform","minecraft","version"])document.getElementById(id).value="";updateFilters();render();area.scrollIntoView({behavior:"smooth",block:"start"})}
function updateFilters(){const platform=document.getElementById("platform"),mc=document.getElementById("minecraft"),version=document.getElementById("version");const productRecords=all.filter(r=>r.product===project);options(platform,unique(productRecords.map(r=>r.platform)).sort(),L("choose"));platform.disabled=!project||!ready;const platformRecords=productRecords.filter(r=>r.platform===platform.value);options(mc,unique(platformRecords.map(r=>r.mc).filter(Boolean)).sort((a,b)=>-cmpVersion(a,b)),L("choose"));mc.disabled=!platform.value;const mcRecords=platformRecords.filter(r=>r.mc===mc.value);options(version,unique(mcRecords.map(r=>"v"+r.version)).sort((a,b)=>-cmpVersion(a,b)),L("chooseVersion"));version.disabled=!mc.value;document.getElementById("selectionNote").textContent=!project?L("noChoose"):!platform.value?L("choosePlatform"):!mc.value?L("chooseMC"):L("chooseVersion")}
function render(){const count=document.getElementById("count"),cards=document.getElementById("downloads"),more=document.getElementById("more");if(!cards)return;cards.replaceChildren();more.hidden=true;if(!project)return;if(loadError){const block=el("div","empty");block.append(el("strong","",L("error")),link("https://github.com/"+REPO+"/releases",L("useReleases"),"textlink"));cards.append(block);count.textContent="–";return}if(!ready){cards.append(el("div","empty",L("loading")));return}const platform=document.getElementById("platform").value,mc=document.getElementById("minecraft").value,version=document.getElementById("version").value;if(!platform||!mc){count.textContent="";return}const matches=all.filter(r=>r.product===project&&r.platform===platform&&r.mc===mc&&(!version||"v"+r.version===version)).sort((a,b)=>cmpVersion(b.version,a.version)||String(b.date).localeCompare(String(a.date)));count.textContent=matches.length+" "+L("files");if(!matches.length){cards.append(el("div","empty",L("none")));return}for(const r of matches.slice(0,visible)){const item=el("article","release"),head=el("div","release-head");head.append(el("h3","",r.product+" v"+r.version),el("span","tag"+(r.approved?" stable":""),L(r.approved?"approved":"test")));item.append(head,el("p","",r.description||"" ));const tags=el("div","tags");for(const t of [r.platform,"MC "+r.mc,r.javaTarget?"Java "+r.javaTarget:"",r.date?new Date(r.date).toLocaleDateString(locale):""])if(t)tags.append(el("span","",t));item.append(tags,el("div","filename",r.filename));const acts=el("div","release-actions");acts.append(link(r.href,L("download"),"primary"),link(r.releaseUrl,L("details"),"secondary"));item.append(acts);cards.append(item)}if(matches.length>visible){more.hidden=false;more.textContent=L("more")+" ("+(matches.length-visible)+")";more.onclick=()=>{visible+=16;render()}}}
function safeUrl(href,type){try{const u=new URL(href);return u.protocol==="https:"&&u.hostname==="github.com"&&u.pathname.startsWith("/"+REPO+"/releases/"+type+"/")?href:""}catch(_){return ""}}
function clean(r){if(!P.includes(r.product)||!r.version||!r.filename||!String(r.filename).endsWith(".jar"))return null;const href=safeUrl(r.href,"download"),releaseUrl=safeUrl(r.releaseUrl,"tag");if(!href||!releaseUrl)return null;const map={paper:"Paper",fabric:"Fabric",neoforge:"NeoForge",forge:"Forge",sponge:"Sponge",quilt:"Quilt",folia:"Folia",spigot:"Spigot",bukkit:"Bukkit",purpur:"Purpur",velocity:"Velocity",bungeecord:"BungeeCord"};const platform=map[String(r.platform).toLowerCase()];if(!platform)return null;return {...r,href,releaseUrl,platform,mc:String(r.mc||""),dev:r.dev===true,approved:r.approved===true}}
async function catalog(){const resp=await fetch("catalog/manifest.json",{cache:"no-cache"});if(!resp.ok)throw Error("Catalog HTTP "+resp.status);const m=await resp.json();if(m.schema!==1||m.repo!==REPO||!Array.isArray(m.pages)||!Number.isSafeInteger(m.count)||m.pages.length!==Math.ceil(m.count/250))throw Error("Invalid manifest");const data=[];for(const page of m.pages){if(!/^catalog\/part-[0-9]{5}\.json$/.test(page.path)||!Number.isInteger(page.count)||page.count<1||page.count>250)throw Error("Invalid page");const res=await fetch(page.path,{cache:"no-cache"});if(!res.ok)throw Error("Missing shard");const j=await res.json();if(j.schema!==1||!Array.isArray(j.entries)||j.entries.length!==page.count)throw Error("Invalid shard");for(const row of j.entries){const entry=clean(row);if(!entry)throw Error("Invalid release entry");data.push(entry)}}if(data.length!==m.count)throw Error("Catalog count mismatch");const seen=new Set();return data.filter(r=>{const key=[r.product,r.platform,r.mc,r.version,r.javaTarget].join("|");if(seen.has(key))return false;seen.add(key);return true})}

/* Separate always-visible search: product browsing does not constrain these results. */
let searchVisible=8;
function searchCard(r){
 const item=el("article","release");
 const head=el("div","release-head");
 head.append(el("h3","",r.product+" v"+r.version),el("span","tag"+(r.approved?" stable":""),L(r.approved?"approved":"test")));
 item.append(head,el("p","",r.description||""));
 const tags=el("div","tags");
 for(const x of [r.platform,"MC "+r.mc,r.javaTarget?"Java "+r.javaTarget:"",r.date?new Date(r.date).toLocaleDateString(locale):""])if(x)tags.append(el("span","",x));
 item.append(tags,el("div","filename",r.filename));
 const buttons=el("div","release-actions");
 buttons.append(link(r.href,L("download"),"primary"),link(r.releaseUrl,L("details"),"secondary"));
 item.append(buttons);
 return item;
}
function renderSearch(){
 const input=document.getElementById("freeSearch"),zone=document.getElementById("searchResults");
 if(!input||!zone)return;
 const q=input.value.trim().toLocaleLowerCase(),title=document.getElementById("searchResultTitle"),counter=document.getElementById("searchCount"),more=document.getElementById("searchMore");
 title.textContent=L(q?"searchResults":"searchInitial");zone.replaceChildren();more.hidden=true;
 if(loadError){const box=el("div","empty");box.append(el("strong","",L("error")),link("https://github.com/"+REPO+"/releases",L("useReleases"),"textlink"));zone.append(box);counter.textContent="";return}
 if(!ready){zone.append(el("div","empty",L("loading")));counter.textContent="";return}
 const terms=q.split(/[\\s,;\\/]+/).filter(Boolean);
 const matched=all.filter(r=>{const searchable=[r.product,r.platform,r.mc,r.version,"v"+r.version,r.javaTarget,"Java "+r.javaTarget,r.filename,r.description].join(" ").toLocaleLowerCase();return terms.every(t=>searchable.includes(t))}).sort((a,b)=>String(b.date).localeCompare(String(a.date))||-cmpVersion(a.version,b.version));
 counter.textContent=q?matched.length+" "+L("files"):L("searchInitial")+" · "+all.length+" "+L("files");
 if(!matched.length){const box=el("div","empty");box.append(el("strong","",L("searchEmpty")),el("p","",L("searchHint")));zone.append(box);return}
 matched.slice(0,searchVisible).forEach(r=>zone.append(searchCard(r)));
 if(matched.length>searchVisible){more.hidden=false;more.textContent=L("more")+" ("+(matched.length-searchVisible)+")";more.onclick=()=>{searchVisible+=12;renderSearch()}}
}

document.addEventListener("DOMContentLoaded",async()=>{initLocale();document.getElementById("freeSearch").addEventListener("input",()=>{searchVisible=8;renderSearch()});document.getElementById("clearSearch").addEventListener("click",()=>{document.getElementById("freeSearch").value="";searchVisible=8;renderSearch();document.getElementById("freeSearch").focus()});document.querySelectorAll(".quick").forEach(b=>b.addEventListener("click",()=>{document.getElementById("freeSearch").value=b.dataset.query;searchVisible=8;renderSearch();document.getElementById("search").scrollIntoView({behavior:"smooth",block:"start"})}));document.querySelectorAll(".product-card").forEach(b=>b.addEventListener("click",()=>choose(b.dataset.product)));for(const id of ["platform","minecraft","version"]){document.getElementById(id).addEventListener("change",()=>{visible=16;if(id==="platform"){document.getElementById("minecraft").value="";document.getElementById("version").value=""}if(id==="minecraft")document.getElementById("version").value="";updateFilters();render()})}document.getElementById("reset").onclick=()=>{project="";document.querySelectorAll(".product-card").forEach(b=>b.setAttribute("aria-pressed","false"));document.getElementById("browser").hidden=true;document.getElementById("products").scrollIntoView({behavior:"smooth",block:"start"})};setLang();try{all=await catalog();ready=true}catch(err){console.warn("Q catalogue unavailable",err);loadError=err.message}updateFilters();render();renderSearch()});
